### ISSUE TITLE
Sharing iP code quality feedback [for @ongzhili]

### ISSUE THREAD

**Issue by soc-se-script** [ongzhili/ip#3]
@ongzhili We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/lamball/Storage.java` lines `168-168`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Storage.java#L168..L168):

```java

                // System.out.println("Line " + index + " replaced successfully.");

```

Example from [`src/main/java/lamball/Storage.java` lines `170-170`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Storage.java#L170..L170):

```java

                // System.err.println("aaaaaaa");

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

Example from [`src/main/java/lamball/Lamball.java` lines `112-181`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Lamball.java#L112..L181):

```java

    public void start(Stage stage) {
        //Step 1. Setting up required components
        String initialDisplayText = this.initialize();

        //The container for the content of the chat to scroll.
        scrollPane = new ScrollPane();
        dialogContainer = new VBox();
        scrollPane.setContent(dialogContainer);


        userInput = new TextField();
        sendButton = new Button("Send");

        AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);

        scene = new Scene(mainLayout);

        stage.setScene(scene);
        stage.show();

        //Step 2. Formatting the window to look as expected
        stage.setTitle("Lamball");
        stage.setResizable(false);
        stage.setMinHeight(600.0);
        stage.setMinWidth(400.0);

        mainLayout.setPrefSize(400.0, 600.0);

        scrollPane.setPrefSize(385, 535);
        scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.ALWAYS);

        scrollPane.setVvalue(1.0);
        scrollPane.setFitToWidth(true);

        //You will need to import `javafx.scene.layout.Region` for this.
        dialogContainer.setPrefHeight(Region.USE_COMPUTED_SIZE);

        userInput.setPrefWidth(325.0);

        sendButton.setPrefWidth(55.0);

        AnchorPane.setTopAnchor(scrollPane, 1.0);

        AnchorPane.setBottomAnchor(sendButton, 1.0);
        AnchorPane.setRightAnchor(sendButton, 1.0);

        AnchorPane.setLeftAnchor(userInput , 1.0);
        AnchorPane.setBottomAnchor(userInput, 1.0);

        dialogContainer.getChildren().add(
                DialogBox.getLamballDialog(
                        new Label(initialDisplayText),
                        new ImageView(duke))
        );

        //Part 3. Add functionality to handle user input.
        sendButton.setOnMouseClicked((event) -> {
            handleUserInput();
        });

        userInput.setOnAction((event) -> {
            handleUserInput();
        });

        //Scroll down to the end every time dialogContainer's height changes.
        dialogContainer.heightProperty().addListener((observable) -> scrollPane.setVvalue(1.0));

    }

```

Example from [`src/main/java/lamball/Storage.java` lines `35-82`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Storage.java#L35..L82):

```java

    public static String obtainSavedFile(Lamball lamb) {
        String returnVal = "";
        File folder = new File(filePath);
        if (!folder.exists()) {
            System.out.println("Folder does not exist. Creating folder...");
            returnVal += "Folder does not exist. Creating folder...\n";
            folder.mkdirs();
        }
        File savedMemo = new File(filePath + defaultMemoName);
        File savedList = new File(filePath + defaultFileName);

        try {
            // List file creation
            if (savedList.createNewFile()) {
                String message = "List created successfully at: " + savedList.getAbsolutePath();
                System.out.println(message);
                returnVal += message + "\n";
            } else {
                assert savedList.exists() : "There should be a list.txt";
                String message = "Seems like I haave helped you before, so no new list is needed!";
                System.out.println(message);
                returnVal += message + "\n\n";
            }

            // Memo file creation
            if (savedMemo.createNewFile()) {
                String message = "Memo created successfully at: " + savedMemo.getAbsolutePath();
                System.out.println(message);
                returnVal += message + "\n";
            } else {
                assert savedMemo.exists() : "There should be a memo.txt";
                String message = "Seems like you have saved memos!";
                System.out.println(message);
                returnVal += message + "\n\n";
            }

            initializeListFromText(savedList, lamb);
            initializeMemo(savedMemo, lamb);
        } catch (IOException e) {
            String errorMessage = "An error occurred while creating the file: " + e.getMessage();
            System.err.println(errorMessage);
            returnVal += errorMessage;
            return returnVal;
        }

        assert returnVal != "" : "return value should not be empty";
        return returnVal;
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2324s2.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/lamball/Lamball.java` lines `65-70`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Lamball.java#L65..L70):

```java

    /**
     * Parse for initial list of commands
     *
     * @param msg Command to parse.
     * @throws LamballParseException if invalid command is provided.
     */

```

Example from [`src/main/java/lamball/Lamball.java` lines `183-187`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/Lamball.java#L183..L187):

```java

    /**
     * Iteration 2:
     * Creates two dialog boxes, one echoing user input and the other containing Duke's reply and then appends them to
     * the dialog container. Clears the user input after processing.
     */

```

Example from [`src/main/java/lamball/TaskList.java` lines `55-59`](https://github.com/ongzhili/ip/blob/57e81215574699bb017d1011828bee1f7e6d822d/src/main/java/lamball/TaskList.java#L55..L59):

```java

    /**
     * Default list printing operation.
     *
     * @return Boolean to continue keeping the bot running.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by ongzhili** [comment]
Fixed!
